### ISSUE TITLE
Create door interaction mechanics, open, close, puzzle done.

### ISSUE THREAD

**Issue by Lambric42** [SchoolOfCode/escape-room-hackathon-room-12-connie-curtis-richard#5]
Definition of done;
Create door sprites for open and closed.
Set door sprite to closed at start of game and shown.
Set door sprite to open when door clicked and broadcast event when clicked.
When puzzle X for door X complete, receive broadcast and hide.

**Comment by CapnDred** [comment]
Completed for first puzzle. This can be copied and pasted with necessary adjustments as needed for other doors.
