### ISSUE TITLE
Create puzzle 1

### ISSUE THREAD

**Issue by Lambric42** [SchoolOfCode/escape-room-hackathon-room-12-connie-curtis-richard#6]
Set all components to hidden at start of game.

When receive broadcast - start puzzle dialogue

Broadcast event to trigger puzzle 1

Puzzle 1 elements spawn

User inputs correct value - dialogue/reward for puzzle complete. broadcast puzzle 1 complete. 
Puzzle 1 elements disappear and can't be interacted with again.

User inputs incorrect value, output informs wrong.
puzzle loops back to start state until correct value received.

**Comment by CapnDred** [comment]
Completed for puzzle 1 and basic structure can be duplicated for future puzzles with necessary amendments
